# Generated by Django 3.1.2 on 2020-10-28 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=50)),
                ('nt', models.IntegerField(default='1')),
                ('date', models.DateField()),
                ('payment', models.BooleanField(default=False)),
                ('tgive', models.BooleanField(default=False)),
                ('trecv', models.BooleanField(default=False)),
            ],
        ),
    ]
